baseURL = 'https://www.isaachill.co.uk'
languageCode = 'en-us'
title = "Isaac Hill"
theme = "hugo-PaperMod"

# Main menu which appears below site header.
# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1

[[menu.main]]
name = "All posts"
url = "/archives"
weight = 2

[[menu.main]]
name = "Projects"
url = "/categories/projects/"
weight = 3

# [[menu.main]]
# name = "Categories"
# url = "/categories/"
# weight = 3

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Search"
url = "/search"
weight = 5



[taxonomies]
  tag = "tags"
  category = "categories"
  # tag = 'project'



[params.homeInfoParams]
Title = "Hi, welcome to my site 💻"
Content = """This is where I advertise myself on the internet; my store front if you will.

📔 Projects | 📮 Blog posts | 📎 CV / Resume"""

[[params.socialIcons]]
name = "LinkedIn"
url = "https://linkedin.com/in/isaac-hill-50a1b4a3"

[[params.socialIcons]]
name = "email"
url = "mailto:isaac@isaachill.co.uk"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/isaachilly"

[[params.socialIcons]]
name = "rss"
url = "https://www.isaachill.co.uk/posts/index.xml"

[params]
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
# ShowShareButtons = true
ShowReadingTime= true
Description = "The personal website, blog and development diary of Isaac Hill."
ShowPostNavLinks=true
ShowToc = true
env= "production"


[outputs]
home = [ "HTML", "RSS", "JSON" ]



[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
